
export const table_data = [
  { 
    sr_no: 1, 
    row_material: 'GHEE', 
    qty: '4.500 kg', 
    final_qty: '4.500', 
    unit: 'KiloGram',
    agency: '',
    place: 'At Venue',
    total_price: 2295.0,
    child_data: [
      { 
        sr_no: 1, 
        function_type: 'DINNER', 
        item_name: 'FULKA ROTI', 
        agency: '', 
        qty: '2',
        unit: 'KiloGram',
        place: 'At Venue',
        date_time:'2025-08-15',
        price: 1020.0,
      },{ 
        sr_no: 2, 
        function_type: 'DINNER', 
        item_name: 'CHUR CHUR NAAN', 
        agency: '', 
        qty: '2',
        unit: 'KiloGram',
        place: 'At Venue',
        date_time:'2025-08-15',
        price: 1020.0,
      },
      { 
        sr_no: 3, 
        function_type: 'DINNER', 
        item_name: 'MATKA DAL RICE', 
        agency: '', 
        qty: '500',
        unit: 'Gram',
        place: 'At Venue',
        date_time:'2025-08-15',
        price: 255.0,
      },
    ]
  },
  { 
    sr_no: 2, 
    row_material: 'TATA SALT ( NAMAK )', 
    qty: '5.500 Kg', 
    final_qty: 5.500, 
    unit: 'KiloGram',
    agency: '',
    place: 'At Venue',
    total_price: 110.0,
    child_data: [
      { 
        sr_no: 1, 
        function_type: 'DINNER', 
        item_name: 'BURMESE KHOWSUEY SOUP', 
        agency: '', 
        qty: '500',
        unit: 'Gram',
        place: 'At Venue',
        date_time:'2025-08-15',
        price: 10.0,
      },{ 
        sr_no: 2, 
        function_type: 'DINNER', 
        item_name: 'GREEN SURTI UNDHIYU', 
        agency: '', 
        qty: '500',
        unit: 'Gram',
        place: 'At Venue',
        date_time:'2025-08-15',
        price: 10.0,
      },
      { 
        sr_no: 3, 
        function_type: 'DINNER', 
        item_name: 'PANEER PASANDA', 
        agency: '', 
        qty: '500',
        unit: 'Gram',
        place: 'At Venue',
        date_time:'2025-08-15',
        price: 10.0,
      },
    ]
  },
  { 
    sr_no: 3, 
    row_material: 'MAIDA', 
    qty: '16.500 Kg', 
    final_qty: 16.500, 
    unit: 'KiloGram',
    agency: 'HARDIK BHAI GAS',
    place: 'At Venue',
    total_price: 462,
    child_data: [
      { 
        sr_no: 1, 
        function_type: 'DINNER', 
        item_name: 'PANEER PASANDA', 
        agency: '', 
        qty: '1.500',
        unit: 'KiloGram',
        place: 'At Venue',
        date_time:'2025-08-15',
        price: 10.0,
      },{ 
        sr_no: 2, 
        function_type: 'DINNER', 
        item_name: 'CHUR CHUR NAAN', 
        agency: '', 
        qty: '500',
        unit: 'Gram',
        place: 'At Venue',
        date_time:'2025-08-15',
        price: 10.0,
      },
      { 
        sr_no: 3, 
        function_type: 'DINNER', 
        item_name: 'PANEER PASANDA', 
        agency: '', 
        qty: '500',
        unit: 'Gram',
        place: 'At Venue',
        date_time:'2025-08-15',
        price: 10.0,
      },
    ]
  },
  { 
    sr_no: 4, 
    row_material: 'SUGAR (SHAKKAR)', 
    qty: '6 Kg', 
    final_qty: 6, 
    unit: 'KiloGram',
    agency: '',
    place: 'At Venue',
    total_price: 210,
    child_data: [
      { 
        sr_no: 1, 
        function_type: 'DINNER', 
        item_name: 'FULKA ROTI', 
        agency: '', 
        qty: '2',
        unit: 'KiloGram',
        place: 'At Venue',
        date_time:'2025-08-15',
        price: 1020.0,
      },{ 
        sr_no: 2, 
        function_type: 'DINNER', 
        item_name: 'CHUR CHUR NAAN', 
        agency: '', 
        qty: '2',
        unit: 'KiloGram',
        place: 'At Venue',
        date_time:'2025-08-15',
        price: 1020.0,
      },
      { 
        sr_no: 3, 
        function_type: 'DINNER', 
        item_name: 'MATKA DAL RICE', 
        agency: '', 
        qty: '500',
        unit: 'Gram',
        place: 'At Venue',
        date_time:'2025-08-15',
        price: 255.0,
      },
    ]
  },
  { 
    sr_no: 5, 
    row_material: 'AJINO MOTO', 
    qty: '750 g', 
    final_qty: 750, 
    unit: 'Gram',
    agency: '',
    place: 'At Venue',
    total_price: 90,
    child_data: [
      { 
        sr_no: 1, 
        function_type: 'DINNER', 
        item_name: 'BURMESE KHOWSUEY SOUP', 
        agency: '', 
        qty: '500',
        unit: 'Gram',
        place: 'At Venue',
        date_time:'2025-08-15',
        price: 10.0,
      },{ 
        sr_no: 2, 
        function_type: 'DINNER', 
        item_name: 'GREEN SURTI UNDHIYU', 
        agency: '', 
        qty: '500',
        unit: 'Gram',
        place: 'At Venue',
        date_time:'2025-08-15',
        price: 10.0,
      },
      { 
        sr_no: 3, 
        function_type: 'DINNER', 
        item_name: 'PANEER PASANDA', 
        agency: '', 
        qty: '500',
        unit: 'Gram',
        place: 'At Venue',
        date_time:'2025-08-15',
        price: 10.0,
      },
    ]
  },
  { 
    sr_no: 6, 
    row_material: 'OIL', 
    qty: '16 L', 
    final_qty: 16, 
    unit: 'Liter',
    agency: 'HARDIK BHAI GAS',
    place: 'At Venue',
    total_price: 3200,
    child_data: [
      { 
        sr_no: 1, 
        function_type: 'DINNER', 
        item_name: 'PANEER PASANDA', 
        agency: '', 
        qty: '1.500',
        unit: 'KiloGram',
        place: 'At Venue',
        date_time:'2025-08-15',
        price: 10.0,
      },{ 
        sr_no: 2, 
        function_type: 'DINNER', 
        item_name: 'CHUR CHUR NAAN', 
        agency: '', 
        qty: '500',
        unit: 'Gram',
        place: 'At Venue',
        date_time:'2025-08-15',
        price: 10.0,
      },
      { 
        sr_no: 3, 
        function_type: 'DINNER', 
        item_name: 'PANEER PASANDA', 
        agency: '', 
        qty: '500',
        unit: 'Gram',
        place: 'At Venue',
        date_time:'2025-08-15',
        price: 10.0,
      },
    ]
  },
  { 
    sr_no: 7, 
    row_material: 'COCONUT MILK TIN', 
    qty: '10 NOS', 
    final_qty: 10, 
    unit: 'NOS',
    agency: '',
    place: 'At Venue',
    total_price: 690,
    child_data: [
      { 
        sr_no: 1, 
        function_type: 'DINNER', 
        item_name: 'FULKA ROTI', 
        agency: '', 
        qty: '2',
        unit: 'KiloGram',
        place: 'At Venue',
        date_time:'2025-08-15',
        price: 1020.0,
      },{ 
        sr_no: 2, 
        function_type: 'DINNER', 
        item_name: 'CHUR CHUR NAAN', 
        agency: '', 
        qty: '2',
        unit: 'KiloGram',
        place: 'At Venue',
        date_time:'2025-08-15',
        price: 1020.0,
      },
      { 
        sr_no: 3, 
        function_type: 'DINNER', 
        item_name: 'MATKA DAL RICE', 
        agency: '', 
        qty: '500',
        unit: 'Gram',
        place: 'At Venue',
        date_time:'2025-08-15',
        price: 255.0,
      },
    ]
  },
];

export const agencies = [
  "TIRUPATI AGRO",
  "jaydeepbhai",
  "RAJADHIRAJ HITESH BHAI",
  "HARDIK BHAI GAS",
  "HITESH DANDI",
  "BANSARI GROCERY",
  "NARESH CHANDRA",
  "SURBHI DAIRY",
  "KAMLESH BHAI",
  "NILESH AQUA BLUE",
  "RICHI RICH BAKERY",
  "SANKET BAKERY",
  "RAM SINGH",
  "JAGDISH BHAI"
];