// Status badge styling, matching the pill design in the design ref
const STATUS_STYLES = {
  Pending:  { dot: "bg-blue-500",   text: "text-blue-700",   bg: "bg-blue-50" },
  Approved: { dot: "bg-green-500",  text: "text-green-700",  bg: "bg-green-50" },
  Rejected: { dot: "bg-red-500",    text: "text-red-700",    bg: "bg-red-50" },
  Draft:    { dot: "bg-gray-400",   text: "text-gray-600",   bg: "bg-gray-100" },
};

const StatusBadge = ({ status }) => {
  const style = STATUS_STYLES[status] || STATUS_STYLES.Draft;
  return (
    <span
      className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium ${style.bg} ${style.text}`}
    >
      <span className={`w-1.5 h-1.5 rounded-full ${style.dot}`} />
      {status}
    </span>
  );
};

const getInitials = (name = "") =>
  name
    .split(" ")
    .map((w) => w[0])
    .join("")
    .slice(0, 2)
    .toUpperCase();

const AVATAR_COLORS = [
  "bg-blue-100 text-blue-700",
  "bg-purple-100 text-purple-700",
  "bg-amber-100 text-amber-700",
  "bg-teal-100 text-teal-700",
];

const avatarColor = (name = "") =>
  AVATAR_COLORS[name.charCodeAt(0) % AVATAR_COLORS.length];

export const columns = (handleEdit, handlePrint, handleView, handleDelete) => [
  {
    accessorKey: "sr_no",
    header: () => "Sr. No.",
    cell: ({ row }) => (
      <span className="text-sm text-gray-600">
        {String(row.original.sr_no).padStart(2, "0")}
      </span>
    ),
    size: 60,
  },
  {
    accessorKey: "requestCode",
    header: () => "Request Code",
    cell: ({ row }) => (
      <span className="text-sm font-medium text-gray-900">
        {row.original.requestCode}
      </span>
    ),
  },
  {
    accessorKey: "startDate",
    header: () => "Start Date",
    cell: ({ row }) => (
      <span className="text-sm text-gray-600">{row.original.startDate}</span>
    ),
  },
  {
    accessorKey: "endDate",
    header: () => "End Date",
    cell: ({ row }) => (
      <span className="text-sm text-gray-600">{row.original.endDate}</span>
    ),
  },
  {
    accessorKey: "generatedByName",
    header: () => "Generated By",
    cell: ({ row }) => {
      const { generatedByName, generatedByRole } = row.original;
      return (
        <div className="flex items-center gap-2">
          
          <span className="text-sm text-gray-800">
            {generatedByName} {generatedByRole}
          </span>
        </div>
      );
    },
  },
  {
    accessorKey: "status",
    header: () => "Status",
    cell: ({ row }) => <StatusBadge status={row.original.status} />,
  },
  {
    accessorKey: "remarks",
    header: () => "Remarks",
    cell: ({ row }) => (
      <span className="text-sm text-gray-600 truncate max-w-[180px] block">
        {row.original.remarks}
      </span>
    ),
  },
  {
    id: "actions",
    header: () => <span className="block text-right">Actions</span>,
    cell: ({ row }) => (
      <div className="flex items-center justify-end gap-1">
        <button
          className="btn btn-sm btn-icon btn-light"
          title="Edit"
          onClick={() => handleEdit(row.original)}
        >
          <i className="ki-filled ki-pencil text-gray-500 text-sm"></i>
        </button>
        <button
          className="btn btn-sm btn-icon btn-light"
          title="Print"
          onClick={() => handlePrint(row.original)}
        >
          <i className="ki-filled ki-printer text-gray-500 text-sm"></i>
        </button>
        <button
          className="btn btn-sm btn-icon btn-light"
          title="View"
          onClick={() => handleView(row.original)}
        >
          <i className="ki-filled ki-document text-gray-500 text-sm"></i>
        </button>
        <button
          className="btn btn-sm btn-icon btn-light"
          title="Delete"
          onClick={() => handleDelete(row.original.id)}
        >
          <i className="ki-filled ki-trash text-red-500 text-sm"></i>
        </button>
      </div>
    ),
  },
];