import { useState, useMemo, useEffect } from "react";
import {
  Search,
  Pencil,
  Eye,
  Printer,
  FileText,
  Trash2,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  CircleCheckBig,
} from "lucide-react";
import { Select, Spin, Modal } from "antd";
import { TableComponent } from "../../../components/table/TableComponent";
import { useNavigate } from "react-router";
import { usePermission } from "../../../hooks/usePermission";
import { FormattedMessage } from "react-intl";
import Swal from "sweetalert2";
// TODO: adjust this import path to match your actual project structure
import { getallpurchasereport, getpurchaseapprovalbyid } from "@/services/apiServices";

const STATUS_STYLES = {
  Pending: "bg-yellow-100 text-yellow-700",
  Approved: "bg-green-100 text-green-700",
  Rejected: "bg-red-100 text-red-600",
};

const PurchaseApprovalList = () => {
  const [searchTerm, setSearchTerm] = useState("");
  const [userFilter, setUserFilter] = useState("all");
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);

  // ── Real data ─────────────────────────────────────────────────────────
  const [requests, setRequests] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  // ── View modal ────────────────────────────────────────────────────────
  const [viewModalOpen, setViewModalOpen] = useState(false);
  const [viewData, setViewData] = useState(null);
  const [viewLoading, setViewLoading] = useState(false);

  const navigate = useNavigate();
  const permissions = usePermission("Purchase Approve");

  // userId lives in localStorage per project convention
  const userId = localStorage.getItem("mainId");

  // TODO: confirm the actual field names returned by /purchase-approval/getAll
  // and adjust this mapping. Fallback chain (res?.data?.data ?? res?.data ?? res)
  // mirrors the pattern used elsewhere in this project.
  const mapRequestRow = (r) => ({
    id: r.id ?? r.purchaseRequestId,
    requestCode: r.requestCode ?? "",
    startDate: r.startDate ?? "",
    endDate: r.endDate ?? "",
    requestBy: r.requestBy ?? "",
    generatedBy: r.generatedBy ?? r.createdByName ?? "",
    status: r.status ?? "Pending",
    remarks: r.remarks ?? "",
  });

  const fetchRequests = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await getallpurchasereport(userId);
      const responseData = res?.data?.data ?? res?.data ?? res;
      // TODO: confirm whether the API returns a bare array or an object with
      // a "content"/list key like the other paginated endpoints in this project.
      const list = Array.isArray(responseData)
        ? responseData
        : responseData?.content ?? [];

      setRequests(list.map(mapRequestRow));
    } catch (err) {
      console.error("Failed to load purchase requests:", err);
      setError(err?.response?.data?.message ?? err?.message ?? "Failed to load requests.");
      setRequests([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRequests();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userId]);

  // Distinct "Generated By" names, derived from whatever came back from the API
  const userFilterOptions = useMemo(() => {
    const names = Array.from(
      new Set(requests.map((r) => r.generatedBy).filter(Boolean))
    );
    return [
      { value: "all", label: "Username" },
      ...names.map((name) => ({ value: name, label: name })),
    ];
  }, [requests]);

  // ── Handlers ──────────────────────────────────────────────────────────
  const handleApprove = (id) => {
    navigate("/purchase/approval-request/add", {
      state: { mode: "approve", requestId: id },
    });
  };

  const handleEdit = (id) => {
    navigate("/purchase/approval-request/add", {
      state: { mode: "edit", requestId: id },
    });
  };

  const handleView = async (id) => {
    setViewModalOpen(true);
    setViewData(null);
    setViewLoading(true);
    try {
      const res = await getpurchaseapprovalbyid(id);
      const data = res?.data?.data ?? res?.data ?? res;
      setViewData(data);
    } catch (err) {
      console.error("Failed to load purchase request details:", err);
      Swal.fire({
        icon: "error",
        title: "Error",
        text: "Failed to load purchase request details.",
      });
      setViewModalOpen(false);
    } finally {
      setViewLoading(false);
    }
  };

  const handlePrint = (id) => {
    console.log("Print request", id);
  };

  const handleDelete = (id) => {
    console.log("Delete request", id);
  };

  // ── Filtering ─────────────────────────────────────────────────────────
  const filteredRequests = useMemo(() => {
    return requests.filter((r) => {
      const matchesSearch =
        !searchTerm ||
        r.requestCode.toLowerCase().includes(searchTerm.toLowerCase()) ||
        r.remarks.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesUser = userFilter === "all" || r.generatedBy === userFilter;
      return matchesSearch && matchesUser;
    });
  }, [requests, searchTerm, userFilter]);

  const totalCount = filteredRequests.length;
  const totalPages = Math.max(1, Math.ceil(totalCount / pageSize));
  const currentPage = Math.min(page, totalPages);
  const pageStart = totalCount === 0 ? 0 : (currentPage - 1) * pageSize + 1;
  const pageEnd = Math.min(currentPage * pageSize, totalCount);

  const pageRows = useMemo(() => {
    const start = (currentPage - 1) * pageSize;
    return filteredRequests.slice(start, start + pageSize);
  }, [filteredRequests, currentPage, pageSize]);

  // ── Table columns (TanStack-shaped, consumed by DataGrid) ───────────────
  const columns = useMemo(
    () => [
      {
        id: "srNo",
        header: "Sr. No.",
        cell: ({ row }) => (
          <span className="text-sm text-slate-500 font-medium">
            {(currentPage - 1) * pageSize + row.index + 1 < 10
              ? `0${(currentPage - 1) * pageSize + row.index + 1}`
              : (currentPage - 1) * pageSize + row.index + 1}
          </span>
        ),
      },
      {
        id: "requestCode",
        accessorKey: "requestCode",
        header: "Request Code",
        cell: ({ getValue }) => (
          <span className="font-semibold text-slate-800 text-sm">{getValue()}</span>
        ),
      },
      {
        id: "startDate",
        accessorKey: "startDate",
        header: "Start Date",
        cell: ({ getValue }) => (
          <span className="text-sm text-slate-600">{getValue()}</span>
        ),
      },
      {
        id: "endDate",
        accessorKey: "endDate",
        header: "End Date",
        cell: ({ getValue }) => (
          <span className="text-sm text-slate-600">{getValue()}</span>
        ),
      },
      {
        id: "requestBy",
        accessorKey: "requestBy",
        header: "Request By",
        cell: ({ getValue }) => (
          <span className="text-sm text-slate-700">{getValue()}</span>
        ),
      },
      {
        id: "status",
        accessorKey: "status",
        header: "Status",
        cell: ({ getValue }) => {
          const value = getValue();
          const normalized = String(value ?? "").trim().toUpperCase();
          const styleKey =
            normalized === "APPROVED" ? "Approved" :
            normalized === "REJECTED" ? "Rejected" :
            "Pending";

          return (
            <span
              className={`inline-block px-3 py-1 rounded-full text-xs font-semibold ${STATUS_STYLES[styleKey]}`}
            >
              {value}
            </span>
          );
        },
      },
      {
        id: "remarks",
        accessorKey: "remarks",
        header: "Remarks",
        cell: ({ getValue }) => (
          <span className="text-sm text-slate-500 block max-w-[220px] truncate">
            {getValue()}
          </span>
        ),
      },
      {
        id: "actions",
        header: "Actions",
        cell: ({ row }) => {
          const request = row.original;
          const isApproved = String(request.status ?? "").toUpperCase() === "APPROVED";
          return (
            <div className="flex items-center justify-center gap-3">
              <button
                onClick={() => handleView(request.id)}
                className="text-slate-400 hover:text-blue-500 transition-colors"
                title="View"
              >
               <i className="ki-filled ki-eye text-primary"></i>
              </button>

              {permissions.add && (
  <button
    onClick={() => handleApprove(request.id)}
 
    aria-label="Approve"
    className="group relative flex items-center justify-center w-8 h-8 rounded-full text-green-700 transition-all hover:opacity-90 shadow-sm"
    
  >
    <CircleCheckBig size={17} />
    <span className="pointer-events-none absolute bottom-full left-1/2 -translate-x-1/2 mb-1.5 whitespace-nowrap rounded-md bg-gray-900 px-2 py-1 text-[11px] font-medium text-white opacity-0 group-hover:opacity-100 transition-opacity z-10">
      Approve
    </span>
  </button>
)}
            </div>
          );
        },
      },
    ],
    [currentPage, pageSize, permissions],
  );

  return (
    <div className="min-h-screen w-full overflow-x-hidden px-6 font-sans">
      <div className="mx-auto space-y-5">
        {/* ── Page Header ── */}
        <div>
          <h1 className="text-2xl font-bold text-slate-900 tracking-tight">
            Purchase Approval
          </h1>
          <p className="text-sm text-slate-400 mt-1">
            Review and approve purchase requests.
          </p>
        </div>

        {/* ── List Card ── */}
        <div className="min-w-0 bg-white rounded-2xl shadow-sm border border-slate-200 overflow-hidden">
          {/* Search + filter row */}
          <div className="flex flex-wrap items-center justify-between gap-3 px-6 py-4 border-b border-slate-100">
            <div className="relative w-full sm:w-80">
              <Search
                size={16}
                className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400"
              />
              <input
                type="text"
                value={searchTerm}
                onChange={(e) => {
                  setSearchTerm(e.target.value);
                  setPage(1);
                }}
                placeholder="Search request..."
                className="w-full pl-10 pr-3 py-2.5 rounded-full border border-slate-200 bg-white text-sm text-slate-700 focus:outline-none focus:ring-2 focus:ring-blue-400 focus:border-transparent transition-all"
              />
            </div>

            <div className="flex flex-wrap items-center gap-2">
              {/* <button
                className="btn btn-primary"
                onClick={() => navigate("/purchase/approval-request/add")}
              >
                <i className="ki-filled ki-plus"></i>{" "}
                <FormattedMessage
                  id="PURCHASE.APPROVAL_REQUEST.ADD"
                  defaultMessage="Add Purchase Request"
                />
              </button> */}
            </div>
          </div>

          {/* Table */}
          {loading ? (
            <div className="px-6 py-16 flex flex-col items-center justify-center gap-3 text-sm text-slate-400">
              <Spin size="large" />
              <span>Loading purchase requests...</span>
            </div>
          ) : error ? (
            <div className="px-6 py-10 text-center text-sm text-red-500">{error}</div>
          ) : totalCount === 0 ? (
            <div className="px-6 py-10 text-center text-sm text-slate-400">
              No purchase requests found.
            </div>
          ) : (
            <TableComponent columns={columns} data={pageRows} hidePagination />
          )}

          {/* Footer / pagination */}
          {!loading && !error && totalCount > 0 && (
            <div className="flex flex-wrap items-center justify-between gap-3 px-6 py-4 border-t border-slate-100">
              <span className="text-xs text-slate-400">
                {`Showing ${pageStart}-${pageEnd} of ${totalCount} requests`}
              </span>

              <div className="flex items-center gap-3">
                <span className="text-xs text-slate-400">Rows per page:</span>
                <Select
                  style={{ width: 72, height: 32 }}
                  value={pageSize}
                  onChange={(value) => {
                    setPageSize(value);
                    setPage(1);
                  }}
                  options={[10, 20, 50].map((n) => ({ value: n, label: String(n) }))}
                />
                <div className="flex items-center gap-1">
                  <button
                    onClick={() => setPage((p) => Math.max(1, p - 1))}
                    disabled={currentPage === 1}
                    className="w-7 h-7 rounded-lg border border-slate-200 flex items-center justify-center text-slate-400 hover:bg-slate-50 disabled:opacity-40 disabled:hover:bg-transparent transition-colors"
                  >
                    <ChevronLeft size={14} />
                  </button>
                  <button
                    onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                    disabled={currentPage === totalPages}
                    className="w-7 h-7 rounded-lg border border-slate-200 flex items-center justify-center text-slate-400 hover:bg-slate-50 disabled:opacity-40 disabled:hover:bg-transparent transition-colors"
                  >
                    <ChevronRight size={14} />
                  </button>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* ── View Modal ── */}
      <Modal
        title={
          <div className="flex items-center gap-2">
            <FileText size={18} className="text-primary" />
            <span>Purchase Request Details</span>
          </div>
        }
        open={viewModalOpen}
        onCancel={() => setViewModalOpen(false)}
        footer={null}
        width={900}
      >
        {viewLoading ? (
          <div className="flex flex-col items-center justify-center gap-3 py-10 text-sm text-slate-400">
            <Spin size="large" />
            <span>Loading...</span>
          </div>
        ) : viewData ? (
          <div className="space-y-5">
            {/* ── Header info ── */}
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-x-6 gap-y-3">
              <div>
                <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-1">
                  Request Code
                </p>
                <p className="text-sm font-semibold text-slate-800">{viewData.requestCode}</p>
              </div>
              <div>
                <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-1">
                  Status
                </p>
                {(() => {
                  const normalized = String(viewData.status ?? "").toUpperCase();
                  const styleKey =
                    normalized === "APPROVED" ? "Approved" :
                    normalized === "REJECTED" ? "Rejected" :
                    "Pending";
                  return (
                    <span
                      className={`inline-block px-3 py-1 rounded-full text-xs font-semibold ${STATUS_STYLES[styleKey]}`}
                    >
                      {viewData.status}
                    </span>
                  );
                })()}
              </div>
              <div>
                <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-1">
                  Start Date
                </p>
                <p className="text-sm text-slate-700">{viewData.startDate}</p>
              </div>
              <div>
                <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-1">
                  End Date
                </p>
                <p className="text-sm text-slate-700">{viewData.endDate}</p>
              </div>
              <div>
                <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-1">
                  Approved By
                </p>
                <p className="text-sm text-slate-700">{viewData.approvedByName || "—"}</p>
              </div>
              <div>
                <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-1">
                  Created At
                </p>
                <p className="text-sm text-slate-700">
                  {viewData.createdAt ? new Date(viewData.createdAt).toLocaleString() : "—"}
                </p>
              </div>
              <div className="col-span-2 sm:col-span-3">
                <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-1">
                  Remarks
                </p>
                <p className="text-sm text-slate-700">{viewData.remarks || "—"}</p>
              </div>
            </div>

        
            {/* ── Line items ── */}
<div>
  <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">
    Items ({viewData.requestDetails?.length ?? 0})
  </p>
  <div className="rounded-xl border border-slate-200 overflow-hidden overflow-x-auto">
    <table className="w-full text-sm whitespace-nowrap">
      <thead className="bg-slate-50">
        <tr>
          <th className="px-3 py-2 text-left text-xs font-bold text-slate-500 uppercase">Item</th>
          <th className="px-3 py-2 text-right text-xs font-bold text-slate-500 uppercase">Avg Daily Cons.</th>
          <th className="px-3 py-2 text-right text-xs font-bold text-slate-500 uppercase">Lead Time</th>
          <th className="px-3 py-2 text-right text-xs font-bold text-slate-500 uppercase">Min Qty</th>
          <th className="px-3 py-2 text-right text-xs font-bold text-slate-500 uppercase">Max Qty</th>
          <th className="px-3 py-2 text-right text-xs font-bold text-slate-500 uppercase">Today's Stock</th>
          <th className="px-3 py-2 text-right text-xs font-bold text-slate-500 uppercase">Req Qty (SYS)</th>
          <th className="px-3 py-2 text-right text-xs font-bold text-slate-500 uppercase">Req Qty</th>
          <th className="px-3 py-2 text-right text-xs font-bold text-slate-500 uppercase">Approved Qty</th>
        </tr>
      </thead>
      <tbody>
        {(viewData.requestDetails ?? []).map((item) => (
          <tr key={item.id} className="border-t border-slate-100">
            <td className="px-3 py-2 font-semibold text-slate-800">{item.rawMaterialName}</td>
            <td className="px-3 py-2 text-right text-slate-500">{item.avgDailyCons ?? "—"}</td>
            <td className="px-3 py-2 text-right text-slate-500">{item.leadTime ?? "—"}</td>
            <td className="px-3 py-2 text-right text-slate-500">{item.minQty ?? "—"}</td>
            <td className="px-3 py-2 text-right text-slate-500">{item.maxQty ?? "—"}</td>
            <td className="px-3 py-2 text-right text-slate-500">{item.todaysStock ?? "—"}</td>
            <td className="px-3 py-2 text-right text-slate-500">
              {item.sysReqQty ?? "—"} {item.sysUnit ?? ""}
            </td>
            <td className="px-3 py-2 text-right text-slate-600">
              {item.requestQty} {item.requestQtyUnitName}
            </td>
            <td className="px-3 py-2 text-right text-slate-600">
              {item.approvedQty} {item.approvedQtyUnitName}
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  </div>
</div>
          </div>
        ) : null}
      </Modal>
    </div>
  );
};

export default PurchaseApprovalList;